# IRIS DATASET

In [5]:
import numpy as np

import pandas as pd
data = pd.read_csv(r"C:\Users\priyadharshini\Iris.csv")
from sklearn.model_selection import train_test_split
#/----------------Function for perceptron algorithm --------------/
def perceptron(c,X,d,w,iter):
    for n in range(1,iter):# Number of iterations  = 20
        print("Iteration :",n)
        for i, x in enumerate(X):
            net = np.dot(X[i],w)
            if net > 0:
                out = 1
            else:
                out = -1
            r = c*(d[i] - out)
            delta_w = r*x
            w = delta_w+w
            print (n, i, w)
    return w
#/---------------------Function for testing the perceptron-----------/

def test_perceptron(final_out,X,w):
    for i,x in enumerate(X):
        net = np.dot(X[i],w)
        if net>0:
            out = 1
        else:
            out = -1
        final_out = final_out+[out]
    return final_out

#---------------Training---------------------------------/
X = data.iloc[:,0:4].values
print ("Inputs", X)
d1=data.iloc[:,4].values
d=np.where(d1=='Iris-setosa',1,-1)
print ("Teacher values", d)
#Splitting the data set
X_train, X_test, y_train, y_test = train_test_split(X, d, test_size=0.33)#computing training and testing sets of x and y
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)
w= ([0,0,0,0])
print ("initial values of weights", w)
c = 1
iterations = 20
print ("Training")
print ("----------")
final_weight = perceptron(c,X_train,y_train,w,iterations)#calculating final_weight
print ("Final sets of weights: ", final_weight)
#-----------------Testing-------------------------------/
final_out = []
print ("Testing")
print ("--------")
final_output = test_perceptron(final_out,X_test,final_weight)#calculating final_output
print ("Final output: ", final_output)
print ("Original Teacher values",y_test)

Inputs [[  1.    5.1   3.5   1.4]
 [  2.    4.9   3.    1.4]
 [  3.    4.7   3.2   1.3]
 [  4.    4.6   3.1   1.5]
 [  5.    5.    3.6   1.4]
 [  6.    5.4   3.9   1.7]
 [  7.    4.6   3.4   1.4]
 [  8.    5.    3.4   1.5]
 [  9.    4.4   2.9   1.4]
 [ 10.    4.9   3.1   1.5]
 [ 11.    5.4   3.7   1.5]
 [ 12.    4.8   3.4   1.6]
 [ 13.    4.8   3.    1.4]
 [ 14.    4.3   3.    1.1]
 [ 15.    5.8   4.    1.2]
 [ 16.    5.7   4.4   1.5]
 [ 17.    5.4   3.9   1.3]
 [ 18.    5.1   3.5   1.4]
 [ 19.    5.7   3.8   1.7]
 [ 20.    5.1   3.8   1.5]
 [ 21.    5.4   3.4   1.7]
 [ 22.    5.1   3.7   1.5]
 [ 23.    4.6   3.6   1. ]
 [ 24.    5.1   3.3   1.7]
 [ 25.    4.8   3.4   1.9]
 [ 26.    5.    3.    1.6]
 [ 27.    5.    3.4   1.6]
 [ 28.    5.2   3.5   1.5]
 [ 29.    5.2   3.4   1.4]
 [ 30.    4.7   3.2   1.6]
 [ 31.    4.8   3.1   1.6]
 [ 32.    5.4   3.4   1.5]
 [ 33.    5.2   4.1   1.5]
 [ 34.    5.5   4.2   1.4]
 [ 35.    4.9   3.1   1.5]
 [ 36.    5.    3.2   1.2]
 [ 37.    5.5   3.5  

C:\Users\priyadharshini\AppData\Local\Temp\ipykernel_10120\1563363624.py:37: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  d=np.where(d1=='Iris-setosa',1,-1)


TypeError: Singleton array array(-1) cannot be considered a valid collection.